dist: xenial
language: python
python:
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: armand33
  password:
    secure: V04p8Jw0VFEfbgyjeqYNyYAWW0+XHlyhv7gsWD25uT3HAYEtP289f9mD9zh2fIk5aT9jC7Id3cBxWHEgG+V6vvE5S1sMgf6qhMimQ+m8E3Sxy2280ooWWWREz7K+gUQDGBa+wDyn94QV4Rm5UsidFnonDauXxrsLiYNuep0OxccV7+xehISC3WyTZ2e7LT3iFzJwy5wbhr52CzcAJbf5f/IqY8Nj9x7yA5xs1UoHm/grCXFkHuG13ac2bdt9zuqpGUMLcyHJelpVFmFshhZkDyClRzODPStKaHtOLlBD1g7A6RlTV/L9oc00d4uMJHPlhAsTfSMPPwu3p5MAukJpnvCKKIN3Sk+LTq1R6TRhOwzjvLt6p2ItOAV2Y/B+x9LeCESEtfEU7E4hK/v77qSQyYGSWe+yM0eZr6kN8P2chrjf7hTG33Iu6SmtsVFfvA9pr/jaBq197HSeOj4M1/XZfmOew4uFgCl4qer9nc68Z9ZXOZPJEG3TtfhaYFW+KGeqGCbTsAQYXSzQZ8ryD1bP6k44w6Q5xpzL6WmS19ihpMFLoyvrUB8vb0lyug3DPz6nL5AgpCniOG8CCblPbIPO7rFUuEuXBx5DxFsPuwasgHGEWli5IPMkdGVeUrj/2VysO6CVtgzQG1S4Q71yyogbdGJ/7tnJ9yVA3TXbHgGKfKc=
  on:
    tags: true
    repo: armand33/wikidatasets
    python: 3.7
